mxm_wifiex: fix next-20230224 Linux Factory rebase build errors
When build wifi driver based on next-20230224 Linux code, will observe
the following build errors.

/work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_shim.c: In function ‘moal_recv_event’:
/work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_shim.c:3475:25: error: too few arguments to function ‘cfg80211_ch_switch_notify’
 3475 |                         cfg80211_ch_switch_notify(priv->netdev, &priv->chan, 0);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_main.h:123,
                 from /work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_shim.c:28:
./include/net/cfg80211.h:8375:6: note: declared here
 8375 | void cfg80211_ch_switch_notify(struct net_device *dev,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:252: /work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_shim.o] Error 1
make[1]: *** [Makefile:2028: /work/mwifiex/mxm_wifiex/wlan_src] Error 2
make[1]: Leaving directory '/work/linux-nxp-rebase'

This is caused by kernel patch b345f0637c00("wifi: cfg80211: include
puncturing bitmap in channel switch events"), now
cfg80211_ch_switch_notify() needs four parameters.

Note: The patch was introduced in L6.2 kernel next tree, but in L6.3
kernel linus tree, so maybe you need to change the kernel version to
L6.3 after we rebase the linux-nxp-rebase to L6.3.

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>