mxm_wifiex: fix L6.7 kernel next tree build errors -- woal_cfg80211_set_beacon
When build wifi driver based on L6.7 kernel next tree, will observe the
following build errors.
These errors caused by kernel patch 66f85d57b710("wifi: cfg80211: modify
prototype for change_beacon") and bb55441c57cc(wifi: cfg80211: split
struct cfg80211_ap_settings), they modify the prototype for
change_beacon() in struct cfg80211_op to accept cfg80211_ap_update
instead of cfg80211_beacon_data so that it can process data in addition
to beacons.

CC [M]  /work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_sta_cfg80211.o
/work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_sta_cfg80211.c:381:26: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_ap_update *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_beacon_data *)’ [-Werror=incompatible-pointer-types]
  381 |         .change_beacon = woal_cfg80211_set_beacon,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~
/work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_sta_cfg80211.c:381:26: note: (near initialization for ‘woal_cfg80211_ops.change_beacon’)

Also fix the build error caused by kernel patch 8e4687f6061e(wifi:
mac80211: rename struct cfg80211_rx_assoc_resp to
cfg80211_rx_assoc_resp_data), it renames the struct
cfg80211_rx_assoc_resp to cfg80211_rx_assoc_resp_data to avoid name
conflict with a function named cfg80211_rx_assoc_resp(). So we need to
make the corresponding changes in wifi driver.

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>