MA-21171-1  mxm_wifiex: Fix kernel update build errors
this is to fix the build error after integrate Q2 CF patch

After kernel merge aosp/android14-6.1, the following error is
encountered:

nxp-mwifiex/mxm_wifiex/wlan_src/mlinux/moal_cfg80211.c:5006:54: error:
too few arguments to function call, expected 4, have 3
cfg80211_ch_switch_notify(priv->netdev, &chandef, 0);

This is caused by kernel patch 541c3b73ddf0("UPSTREAM:
wifi: cfg80211: include puncturing bitmap in channel
switch events"), now cfg80211_ch_switch_notify() needs
four parameters.

Change-Id: I55ec827d696562d644f99adebc6b92b103be06ca
Signed-off-by: yunjie <yunjie.jia@nxp.com>