MA-21171 mxm_wifiex: Fix kernel update build errors
After kernel merge aosp/android14-6.1, the following error is encountered:

nxp-mwifiex/mxm_wifiex/wlan_src/mlinux/moal_cfg80211.c:5006:54: error: too few arguments to function call, expected 4, have 3
cfg80211_ch_switch_notify(priv->netdev, &chandef, 0);

This is caused by kernel patch 541c3b73ddf0("UPSTREAM:
wifi: cfg80211: include puncturing bitmap in channel
switch events"), now cfg80211_ch_switch_notify() needs
four parameters.

Change-Id: I343a89b8466971f486f0ce8937c1612dec5618fa
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>