MA-23485 [All platform] Android-15 kernel 6.12 WiFi compile error
Reason: new compile warning cast-function-type-strict opened in new
6.12.y, change the parameter type
Tested: on 8mq

error info:
vendor/nxp-opensource/nxp-mwifiex/mlinux/moal_wext.c:3311:2: error: cast
from 'int (*)(struct net_device *, struct iw_reques t_info *, struct
iw_param *, char *)' to  'iw_handler' (aka 'int (*)(struct net_device *,
struct iw_request_info *, union iwreq_data *, char *)') converts to
incompatible function type [-Werror,-Wcast-function-type-strict] 3311 |
(iw_handler)woal_set_scan, /* SIOCSIWSCAN */

Change-Id: I062cb3f1697753331c26115ad192825c7600a07d
Signed-off-by: yunjie <yunjie.jia@nxp.com>