mxm_wifiex: fix L6.6 kernel next tree build errors
When build wifi driver based on L6.6 kernel next tree, will observe the
following build errors.
These errors caused by kernel patch 076fc8775daf("wifi: cfg80211: remove
wdev mutex"), it removes mtx from struct wireless_dev and uses wiphy
mutex instead.

CC [M]  /work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_main.o
/work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_main.c: In function ‘woal_evt_work_queue’:
/work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_main.c:11361:47: error: ‘struct wireless_dev’ has no member named ‘mtx’
11361 |                         mutex_lock(&priv->wdev->mtx);
      |                                               ^~
/work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_main.c:11364:49: error: ‘struct wireless_dev’ has no member named ‘mtx’
11364 |                         mutex_unlock(&priv->wdev->mtx);
      |                                                 ^~
make[3]: *** [scripts/Makefile.build:243: /work/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_main.o] Error 1
make[2]: *** [/work/linux-upstream-next/Makefile:1913: /work/mwifiex/mxm_wifiex/wlan_src] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/work/linux-upstream-next'
make: *** [Makefile:598: default] Error 2

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>