mxm_wifiex: fix build error on L7.1.0 kernel next tree
When build wifi driver based on L7.1.0 kernel next tree, will observe the
following build error. It is caused by the upstream patch:
4dbd1829045e ("wifi: cfg80211: Add MAC address filter to remain_on_channel")
Need to change corresponding API here to avoid the build break.

Build error logs:
mlinux/moal_sta_cfg80211.c:553:30: error: initialization of ‘int (*)(struct wiphy *, struct wireless_dev *, struct ieee80211_channel *, unsigned int,  u64 *, const u8 *)’ {aka ‘int (*)(struct wiphy *, struct wireless_dev *, struct ieee80211_channel *, unsigned int,  long long unsigned int *, const unsigned char *)’} from incompatible pointer type ‘int (*)(struct wiphy *, struct wireless_dev *, struct ieee80211_channel *, unsigned int,  u64 *)’ {aka ‘int (*)(struct wiphy *, struct wireless_dev *, struct ieee80211_channel *, unsigned int,  long long unsigned int *)’} [-Wincompatible-pointer-types]
  553 |         .remain_on_channel = woal_cfg80211_remain_on_channel,
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mlinux/moal_sta_cfg80211.c:553:30: note: (near initialization for ‘woal_cfg80211_ops.remain_on_channel’)
mlinux/moal_sta_cfg80211.c:262:1: note: ‘woal_cfg80211_remain_on_channel’ declared here
  262 | woal_cfg80211_remain_on_channel(struct wiphy *wiphy,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[4]: *** [linux-nxp-rebase/scripts/Makefile.build:289: mlinux/moal_sta_cfg80211.o] Error 1

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>