mxm_wifiex: fix L6.1.55 kernel build break
When build wifi driver based on L6.1.55 kernel, will observe the
following build error.

| mxm_wifiex/wlan_src/mlinux/moal_sta_cfg80211.c:10345:36: error: 'REGULATORY_IGNORE_STALE_KICKOFF' undeclared (first use in this function)
| 10345 |         wiphy->regulatory_flags |= REGULATORY_IGNORE_STALE_KICKOFF;
|       |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This error caused by kernel patch e8c2af660ba0("wifi: cfg80211: fix
regulatory disconnect with OCB/NAN") remove the
REGULATORY_IGNORE_STALE_KICKOFF flag.

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>